
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kriiishamtic/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - cart
      - user
      - payment
      - shipping

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: kriiishamtic/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db

  redis:
    image: kriiishamtic/redis:7
    container_name: redis
    volumes:
      - redis:/data

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: kriiishamtic/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    image: kriiishamtic/rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: kriiishamtic/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    image: kriiishamtic/cart:v1
    container_name: cart
    depends_on:
      - mongodb
      - catalogue
      - user

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: kriiishamtic/user:v1
    container_name: user
    depends_on:
      - redis

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: kriiishamtic/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq

  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    image: kriiishamtic/shipping:v1
    container_name: shipping
    depends_on:
      - mysql

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

networks:
  default:
    name: roboshop
    driver: bridge